name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'mkv_episode_matcher/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/documentation.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install .
          
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
